/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppMembersIdRouteImport } from './routes/app.members.$id'
import { Route as AppCheckinEventIdRouteImport } from './routes/app.checkin.$eventId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppCheckinEventIdRoute = AppCheckinEventIdRouteImport.update({
  id: '/checkin/$eventId',
  path: '/checkin/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app/checkin/$eventId': typeof AppCheckinEventIdRoute
  '/app/members/$id': typeof AppMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app/checkin/$eventId': typeof AppCheckinEventIdRoute
  '/app/members/$id': typeof AppMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/events': typeof AppEventsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/organization': typeof AppOrganizationRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/training': typeof AppTrainingRoute
  '/app/checkin/$eventId': typeof AppCheckinEventIdRoute
  '/app/members/$id': typeof AppMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/accounts'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/events'
    | '/app/fees'
    | '/app/members'
    | '/app/organization'
    | '/app/reports'
    | '/app/settings'
    | '/app/training'
    | '/app/checkin/$eventId'
    | '/app/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/accounts'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/events'
    | '/app/fees'
    | '/app/members'
    | '/app/organization'
    | '/app/reports'
    | '/app/settings'
    | '/app/training'
    | '/app/checkin/$eventId'
    | '/app/members/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/accounts'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/events'
    | '/app/fees'
    | '/app/members'
    | '/app/organization'
    | '/app/reports'
    | '/app/settings'
    | '/app/training'
    | '/app/checkin/$eventId'
    | '/app/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members/$id': {
      id: '/app/members/$id'
      path: '/$id'
      fullPath: '/app/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/checkin/$eventId': {
      id: '/app/checkin/$eventId'
      path: '/checkin/$eventId'
      fullPath: '/app/checkin/$eventId'
      preLoaderRoute: typeof AppCheckinEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMembersRouteChildren {
  AppMembersIdRoute: typeof AppMembersIdRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersIdRoute: AppMembersIdRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppCheckinEventIdRoute: typeof AppCheckinEventIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppFeesRoute: AppFeesRoute,
  AppMembersRoute: AppMembersRouteWithChildren,
  AppOrganizationRoute: AppOrganizationRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppCheckinEventIdRoute: AppCheckinEventIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
